version: '3.8'
services:
  app:
    container_name: api-${PROJECT_NAME}
    build: 
      context: .
      target: production
      args:
        - PORT=3000
    ports:
      - "${PORT_POD}:3000"     
    env_file:
      - .env
    depends_on:
      - db
  app-dev:
    container_name: api-smart-logistic-dev
    restart: unless-stopped
    build: 
      context: .
      target: dev
      args:
        - PORT=4000
    ports:
      - "${PORT}:4000"
      - "9229:9229"
    volumes:
      - ./api:/app
      - ./api/node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - db
  db: 
    image: mysql:8.0
    container_name: db-${PROJECT_NAME}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password   
    ports:
      - '${MYSQL_SERVER_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=America/Guatemala
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql  
    env_file:
      - .env

volumes:
  node_modules:


  