version: '3.7'
services:
  app:
    container_name: node-${PROJECT_NAME}
    build: 
      context: .
      target: production
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"     
    env_file:
      - ./api/.env
  app-dev:
    container_name: node-dev-${PROJECT_NAME}
    restart: unless-stopped
    build: 
      context: .
      target: dev
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    volumes:
      - ./api:/project
      - ./api/node_modules:/project/node_modules
    env_file:
      - ./api/.env
  mysql:
    image: mysql:8.0
    container_name: MYSQL-${PROJECT_NAME}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_SERVER_PORT}:3306
    environment:
      - MYSQL_DATABASE: ${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      - TZ: America/Guatemala
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
    env_file:
      - .env
volumes:
  node_modules: