version: '3.8'
services:
  db: 
    image: mysql:8.0
    container_name: db-${PROJECT_NAME}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password   
    ports:
      - '${MYSQL_SERVER_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=America/Guatemala
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql  
    env_file:
      - .env
  app:
    container_name: api-${PROJECT_NAME}
    restart: unless-stopped
    build: 
      context: .
      target: production
      args:
        - PORT=4002
    ports:
      - "${PORT_POD}:4002"     
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api/uploads/files:/app/uploads/files
      - ./api/uploads/images:/app/uploads/images
 
  web: 
    container_name: web-${PROJECT_NAME}
    restart: unless-stopped
    build: 
      context: ./web/
      args:
        - PORT=80
        - VITE_API_URL=${VITE_API_URL}
        - VITE_FIREBASE_TOKEN=${VITE_FIREBASE_TOKEN}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
    ports:
      - "${PORT_WEB}:80"     
    env_file:
      - .env
    depends_on:
      - app

volumes:
  node_modules:


  