### GET CRANE
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/crane
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD CRANE
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/crane
Content-Type: application/json
Authorization: Bearer {{token}}

{   
    "grua": "Erixsone",
    "id_subasta": 1
}

### UPDATE CRANE
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/crane/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "estado": true,
    "grua": "Erixsone",
    "id_subasta": 2
}