### GET AUTIONS
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD AUTIONS
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "PHILLY EAST CP",
    "crane_rate": 250,
    "state_id": 38,
    "sede_id": 1
}

### UPDATE AUTIONS
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "PHILLY CP",
    "crane_rate": 250
}