### GET AUTIONS
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD AUTIONS
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "subasta": "PA  EAST",
    "alias": "EAST"
}

### UPDATE AUTIONS
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/aution/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "subasta": "PA  EAST",
    "alias": "EAST",
    "estado": true
}