### GET CUSTOMER
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer
Content-Type: application/json
Authorization: Bearer {{token}}

### GET CUSTOMER BY ID
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer/2
Content-Type: application/json
Authorization: Bearer {{token}}

### GET CUSTOMER PAGINATION DATA
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer/pagination
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "orderField": "id_cliente",
    "orderDirection": "ASC",
    "filter": ""
}

### ADD CUSTOMER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "El Marzo",
    "phone_number": "6019521325",
    "landline": "3121286800",
    "address": "1600 Fake Street",
    "nit": "CF",
    "dpi": "2271023980101",
    "email": "test@example.us",
    "customer_type_id": 1
}

### EDIT CUSTOMER
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "El Marzo",
    "phone_number": "6019521325",
    "landline": "3121286800",
    "address": "1600 Fake Street",
    "nit": "CF",
    "dpi": "2271023980101",
    "email": "test@example.us",
    "customer_type_id": 1
}

### LOGIN
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer/login
Content-Type: application/json

{
    "email": "test@example.us"
}