### ADD TYPE OF CUSTOMER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer-type
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "tipo_cliente": "Particular"  
}

### GET TYPE OF CUSTOMER
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/customer-type
Content-Type: application/json
Authorization: Bearer {{token}}