### GET notificaciones
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/notification
Content-Type: application/json  
Authorization: Bearer {{token}}

### GET notificaciones por cliente
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/notification/customer/1
Content-Type: application/json
Authorization: Bearer {{token}}

### GET notificaciones por usuario
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/notification/user/1
Content-Type: application/json
Authorization: Bearer {{token}}

# las prioridades son: LOW, MEDIUM, HIGH
# el path es opcional y se usa el path de la tabla menu
# la notificacion puede ir libre o llevar el id del cliente o el usaurio o una combinacion de ambos
### POST add notificacion
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/notification
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "para un cliente en particular ",
    "description": "este contenido es muy importante",
    "priority": "HIGH",
    "customer_id": 1
}

### PUT update notificacion
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/notification/94e3ff84-5920-4573-a379-1a53acc5c93e
Content-Type: application/json
Authorization: Bearer {{token}}

### TEST NOTIFICATION PUSH
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/test-notification/cT9KSdxsrYpmgpDZsa27PK:APA91bFBV-stQmZxkOLqM7ll6YoRpOPj0BE-PYKdgmMSUy_CuMSAIAjnfYWLZh7Wp3x9KQQJp6z_QrVHPYNn6sqbXboKq8J5v3Gy36bu9MaUha-pwRPc0t8
Content-Type: application/json
