### GET ORDER PAPER
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/order-paper
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ORDER PAPER STATUS
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/order-paper/status
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ORDER PAPER BY ID
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/order-paper/1
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD ORDER PAPER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/order-paper
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Pedido de vehículo",
    "description": "Descripción del pedido",
    "date": "2025-04-10 10:00:00",
    "user_id": 1,
    "status_id": 1,
    "customer_id": 1
}

### UPDATE ORDER PAPER
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/order-paper/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Pedido de vehículo",
    "description": "Descripción del pedido",
    "user_id": 1,
    "status_id": 1,
    "customer_id": 1
}