### GET AUTIONS
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/port
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD AUTIONS
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/port
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "puerto": "DELAWARE"
}

### UPDATE AUTIONS
PUT  {{protocol}}://{{host}}:{{port}}/api/{{version}}/port/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "puerto": "DELAWARE",
    "estado": true
}