### GET PROFILE
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

### GET ALL ROLES
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/profile/roles
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD PROFILE
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Vendedor"
}

### UPDATE PROFILE
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/profile/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Vendedor",
    "is_active": false
}