### GET QUOTERS
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/quoter
Content-Type: application/json
Authorization: Bearer {{token}}

### GET PDF
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/quoter/pdf
Content-Type: application/json