### GET 
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/transport-rate
Content-Type: application/json
Authorization: Bearer {{token}}

### GET BY ID
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/transport-rate/1d507b8c-1229-4557-b9f6-21bfc038ed57
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD 
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/transport-rate
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rate": 950,
    "is_active": true,
    "user_id": 1,
    "vehicle_type_id": 2,
    "transport_type_id": 2,
    "headquarter_id": 1,
    "customer_type_id": 1
}

### UPDATE 
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/transport-rate/befdd233-b926-4be6-9a2f-c004e3395479
Content-Type: application/json
Authorization: Bearer {{token}}

{   
    "vehicle_type_id": 1
}

### GET RATE FILER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/transport-rate/get-rate
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "customer_type_id": 1,
    "transport_type_id": 2,
    "vehicle_type_id": 3,
    "headquarter_id": 1
}