### LOGIN
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "abc123**"
}

### ADD USER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Alejandra ramirez",
    "username": "a.ramirez",
    "password": "abc123**",
    "phone_number": "--sin telefono--",
    "email": "-- sin correo --",
    "profile_id": 3,
    "headquarter_id": 1
}

### GET ALL USERS 
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

### GET USER BY ID
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/user/2
Content-Type: application/json
Authorization: Bearer {{token}}

### POST FORGOT PASSWORD
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/forgot-password
Content-Type: application/json

{
    "email": "mortegalex27@gmail.com"
}
