### LOGIN
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/login
Content-Type: application/json

{
    "username": "admin",
    "password": "abc123**"
}

### ADD USER
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Marlon Ortega",
    "username": "m.ortega",
    "password": "abc123**",
    "phone_number": "--sin telefono--",
    "email": "m.ortega@mail.com",
    "profile_id": 1
}

### GET ALL USERS 
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

### POST FORGOT PASSWORD
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/forgot-password
Content-Type: application/json

{
    "email": "mortegalex27@gmail.com"
}
