### GET
GET {{protocol}}://{{host}}:{{port}}/api/{{version}}/vehicle-type
Content-Type: application/json
Authorization: Bearer {{token}}

### ADD
POST {{protocol}}://{{host}}:{{port}}/api/{{version}}/vehicle-type
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "tipo_vehiculo": "Sedan"
}

### UPDATE
PUT {{protocol}}://{{host}}:{{port}}/api/{{version}}/vehicle-type/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "puerto": "Sedan",
    "estado": true
}