-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 11:59:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema smart_logistic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smart_logistic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smart_logistic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `smart_logistic` ;

-- -----------------------------------------------------
-- Table `smart_logistic`.`tipo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`tipo_cliente` (
  `id_tipo_cliente` INT NOT NULL AUTO_INCREMENT,
  `tipo_cliente` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(100) NOT NULL,
  `telefono_celular` VARCHAR(45) NOT NULL,
  `telefono_fijo` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `dpi` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `id_tipo_cliente` INT NULL DEFAULT NULL,
  `porcentaje_costo` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  INDEX `FK_a22bfd4e0c0bf10004a83a66547` (`id_tipo_cliente` ASC),
  CONSTRAINT `FK_a22bfd4e0c0bf10004a83a66547`
    FOREIGN KEY (`id_tipo_cliente`)
    REFERENCES `smart_logistic`.`tipo_cliente` (`id_tipo_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`archivo_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`archivo_cliente` (
  `id_archivo` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(200) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `id_cliente` INT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_archivo`),
  INDEX `FK_decb9d26697af71a668a01ada66` (`id_cliente` ASC),
  CONSTRAINT `FK_decb9d26697af71a668a01ada66`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `smart_logistic`.`cliente` (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`tipo_vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`tipo_vehiculo` (
  `id_tipo_vehiculo` INT NOT NULL AUTO_INCREMENT,
  `tipo_vehiculo` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `porcentaje_costo` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tipo_vehiculo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`perfil` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(255) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `id_perfil` INT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `IDX_9921cd8ed63a072b8f93ead80f` (`usuario` ASC),
  INDEX `FK_a2fb58aab02985cc8264cd3b034` (`id_perfil` ASC),
  CONSTRAINT `FK_a2fb58aab02985cc8264cd3b034`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `smart_logistic`.`perfil` (`id_perfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`subasta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`subasta` (
  `id_subasta` INT NOT NULL AUTO_INCREMENT,
  `subasta` VARCHAR(45) NOT NULL,
  `alias` VARCHAR(45) NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_subasta`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`grua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`grua` (
  `id_grua` INT NOT NULL AUTO_INCREMENT,
  `grua` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `id_subasta` INT NULL DEFAULT NULL,
  `costo` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `moneda` VARCHAR(10) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_grua`),
  INDEX `FK_8d9a50082d6b98a8d563a9d09f3` (`id_subasta` ASC),
  CONSTRAINT `FK_8d9a50082d6b98a8d563a9d09f3`
    FOREIGN KEY (`id_subasta`)
    REFERENCES `smart_logistic`.`subasta` (`id_subasta`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`puerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`puerto` (
  `id_puerto` INT NOT NULL AUTO_INCREMENT,
  `puerto` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `costo_embarque` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `costo_aduanal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_puerto`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`cotizacion` (
  `id_cotizacion` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `anio` VARCHAR(45) NOT NULL,
  `costos` JSON NULL DEFAULT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `id_cliente` INT NOT NULL,
  `id_vendedor` INT NOT NULL,
  `id_tipo_vehiculo` INT NOT NULL,
  `id_puerto` INT NULL DEFAULT NULL,
  `id_grua_usd` INT NULL DEFAULT NULL,
  `id_grua_gt` INT NULL DEFAULT NULL,
  `id_subasta` INT NULL DEFAULT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cotizacion`),
  INDEX `FK_e1c19b8ad84f6fcf4f71632a18c` (`id_cliente` ASC),
  INDEX `FK_3f111d4d371b2b58fb0f236893c` (`id_vendedor` ASC),
  INDEX `FK_2d79d01aa19f489ced16777240c` (`id_tipo_vehiculo` ASC),
  INDEX `FK_92b89e18614f01954b5b2a793cc` (`id_puerto` ASC),
  INDEX `FK_8aaff2b70c87e41f53bfdceb89c` (`id_grua_usd` ASC),
  INDEX `FK_f08ef4f4ffc0f96aafb0765b6d1` (`id_grua_gt` ASC),
  INDEX `FK_6dd38a6bb022d787002de312b42` (`id_subasta` ASC),
  CONSTRAINT `FK_2d79d01aa19f489ced16777240c`
    FOREIGN KEY (`id_tipo_vehiculo`)
    REFERENCES `smart_logistic`.`tipo_vehiculo` (`id_tipo_vehiculo`),
  CONSTRAINT `FK_3f111d4d371b2b58fb0f236893c`
    FOREIGN KEY (`id_vendedor`)
    REFERENCES `smart_logistic`.`usuario` (`id_usuario`),
  CONSTRAINT `FK_6dd38a6bb022d787002de312b42`
    FOREIGN KEY (`id_subasta`)
    REFERENCES `smart_logistic`.`subasta` (`id_subasta`),
  CONSTRAINT `FK_8aaff2b70c87e41f53bfdceb89c`
    FOREIGN KEY (`id_grua_usd`)
    REFERENCES `smart_logistic`.`grua` (`id_grua`),
  CONSTRAINT `FK_92b89e18614f01954b5b2a793cc`
    FOREIGN KEY (`id_puerto`)
    REFERENCES `smart_logistic`.`puerto` (`id_puerto`),
  CONSTRAINT `FK_e1c19b8ad84f6fcf4f71632a18c`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `smart_logistic`.`cliente` (`id_cliente`),
  CONSTRAINT `FK_f08ef4f4ffc0f96aafb0765b6d1`
    FOREIGN KEY (`id_grua_gt`)
    REFERENCES `smart_logistic`.`grua` (`id_grua`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `menu` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `es_mantenimiento` TINYINT NOT NULL DEFAULT '0',
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `permiso` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT '1',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_edicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `smart_logistic`.`perfil_memu_permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smart_logistic`.`perfil_memu_permiso` (
  `id` VARCHAR(36) NOT NULL,
  `id_perfil` INT NULL DEFAULT NULL,
  `id_menu` INT NULL DEFAULT NULL,
  `id_permiso` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_061b6bd30531df70052fddda097` (`id_perfil` ASC),
  INDEX `FK_2eff4d714f8094adb243a1e5906` (`id_menu` ASC),
  INDEX `FK_77dfed8980e4d50afc8456d8de9` (`id_permiso` ASC),
  CONSTRAINT `FK_061b6bd30531df70052fddda097`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `smart_logistic`.`perfil` (`id_perfil`),
  CONSTRAINT `FK_2eff4d714f8094adb243a1e5906`
    FOREIGN KEY (`id_menu`)
    REFERENCES `smart_logistic`.`menu` (`id_menu`),
  CONSTRAINT `FK_77dfed8980e4d50afc8456d8de9`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `smart_logistic`.`permiso` (`id_permiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
